version: "3"

services:
  #################################
  #      Setup node container     #
  #################################
  server:
    container_name: vrse-api
    build: ./server
    ports:
      - "3000:3000" # Expose API port
      - "9229:9229" # Expose Node process debug port (disable in production)
    environment: # Set ENV vars
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - PORT=3000
    command: npm start

  #################################
  #     Setup client container    #
  #################################
  client:
    container_name: vrse-client
    build: ./client
    environment:
      - REACT_APP_PORT=8000
    ports:
      - 8000:8000
    volumes:
      - ./client/src:/usr/src/app/client/src
      - ./client/public:/usr/src/app/client/public
    links:
      - server
    command: npm start
